name: carebase
description: "Aplicativo de gestão de pacientes offline para profissionais da saúde."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Ícones no estilo iOS
  cupertino_icons: ^1.0.8

  # Gerenciamento de estado
  provider: ^6.1.1

  # Banco de dados local (opcional para usar depois)
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.2

  # Salvando preferências (tema, etc.)
  shared_preferences: ^2.2.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Para adicionar imagens futuramente
  # assets:
  #   - assets/images/

  # Para adicionar fontes customizadas futuramente
  # fonts:
  #   - family: NomeDaFonte
  #     fonts:
  #       - asset: fonts/NomeDaFonte-Regular.ttf
